# Numpy入门

In [166]:
import  numpy as np
numpy.__version__
L=list(range(10)) #创建整型值列表
type(L[0])

int

In [167]:
L2=[str(c) for c in L]
print(L2)

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


In [168]:
type(L2[0])

str

In [169]:
L3=[True,3,'2',2.0]
[type(i) for i in L3]


[bool, int, str, float]

# python中的固定类型数组

In [53]:
import array

In [57]:
l=list(range(10))
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [62]:
a=array.array('f',l) #'f'为数据类型码，表示数据为浮点型
print(a)

array('f', [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0])


# 从python列表创建数组

In [64]:
import numpy as np

In [66]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [69]:
np.array([3.14,2,5,6]) #numpy中要求数组的数据类型必须一致，如果不匹配，数据类型将会向上转换。此处整形被转换为浮点型。

array([3.14, 2.  , 5.  , 6.  ])

In [72]:
np.array([1,2,3,4],dtype='float32') #如果希望明确设置数据类型，可以使用dtype关键字。

array([1., 2., 3., 4.], dtype=float32)

In [74]:
#不同于python的list.numpy中的数组可以被指定为多维。
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [77]:
list1=[[1,2,3],[4,5,7],[8,9,0],0]#难道这不是二维列表吗？
print(list1)

[[1, 2, 3], [4, 5, 7], [8, 9, 0], 0]


# 从头创建数组

In [83]:
np.zeros(10,dtype=int) #创建长度为10的数组，数组的值都是0，整型。

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [85]:
np.ones((3,5),dtype=float)  #创建3*5的数组，数组的值都是1，浮点型。

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [87]:
np.full((3,5),3.14) # #创建3*5的数组，数组的值都是3.14，浮点型。

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [91]:
np.arange(0,20,2) #创建一个线性序列，步长为2.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [94]:
np.linspace(0,1,5) #选取使0到1均匀分配的5个数。

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [97]:
np.random.random((3,3)) #3*3的，在0到1的随机数组成的数组

array([[0.55409802, 0.29701866, 0.18180883],
       [0.97602031, 0.1934627 , 0.65723065],
       [0.92287798, 0.68705809, 0.62499837]])

In [100]:
np.random.normal(0,1,(3,3))# 创建3*3的，均值为0，方差为1的正态分布的随机数数组

array([[ 0.521766  , -0.0937112 ,  0.43843805],
       [-0.77661775, -1.26167962,  0.68055982],
       [ 0.83603323,  0.04750462,  0.8531773 ]])

In [103]:
np.random.randint(0,10,(3,3)) #创建一个3*3维，数值属于[0,10)的整数数组

array([[1, 9, 4],
       [4, 4, 7],
       [2, 8, 8]])

In [106]:
np.eye(3) #创建一个3*3的单位矩阵

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [114]:
np.empty(3)

array([1., 1., 1.])

# 2.2 Numpy数组基础



## Numpy数组属性

In [120]:
import numpy as np
np.random.seed(0)#设置随机数种子

In [144]:
x1=np.random.randint(10,size=6)
x2=np.random.randint(10,size=(3,4))
x3=np.random.randint(10,size=(3,4,5))
print('x3 ndim',x3.ndim) #数组维度
print('x3 shape',x3.shape) #每个维度的大小
print('x3 size',x3.size) #数组总大小
print(x3)
print(x1)

x3 ndim 3
x3 shape (3, 4, 5)
x3 size 60
[[[6 9 4 1 5]
  [9 7 1 3 5]
  [7 3 6 6 7]
  [9 1 9 6 0]]

 [[3 8 4 1 4]
  [5 0 3 1 4]
  [4 4 0 0 8]
  [4 6 9 3 3]]

 [[2 1 2 1 3]
  [4 1 1 0 7]
  [8 4 3 5 6]
  [3 2 9 8 1]]]
[9 8 3 6 1 7]


In [135]:
print('dtype',x3.dtype)#打印数组数据类型
print('itemsize',x3.itemsize,'bytes')#打印数组最小元素的字节大小
print('nbytes',x3.nbytes,'bytes')#打印数组总字节大小

dtype int32
itemsize 4 bytes
nbytes 240 bytes


## 数组索引：获取单个元素

In [145]:
x1

array([9, 8, 3, 6, 1, 7])

In [163]:
x1[-6]
x1[5]
#numpy一维数组中元素的获取与标准列表索引类似.

7

In [171]:
x2

array([[4, 9, 2, 0],
       [8, 2, 7, 8],
       [4, 4, 1, 7]])

In [179]:
x2[2,3]#使用，分割的索引元组来获取元素，[i,j]代表第i+1行，j+1列的元素

7

In [182]:
x2[2,3]=9
print(x2)
# 使用这种方式也可以修改元素的值

[[4 9 2 0]
 [8 2 7 8]
 [4 4 1 9]]


In [188]:
print(x1)

[3 8 3 6 1 7]


In [194]:
x1[0]=6.14
print(x1)
#numpy数组元素类型是固定的，当插入值为不同类型数据时，新值类型会被自动转化为元组固定类型，且没有提示。

[6 8 3 6 1 7]


## 数组切片：获取子数组

In [201]:
list1=[5,4,3,2,1]
list1[2:4]

[3, 2]

一维数组    ：  x[start:stop:step] 如果三个参数都未指定，默认值：start=0，stop=ndim数组维度，step=1

In [210]:
x0=list(range(10))
print(x0)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [213]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [221]:
x[:5]

array([0, 1, 2, 3, 4])

In [224]:
x[5:]

array([5, 6, 7, 8, 9])

In [226]:
x[4:7]

array([4, 5, 6])

In [228]:
x[::2]

array([0, 2, 4, 6, 8])

In [230]:
x[1::2]

array([1, 3, 5, 7, 9])

当步长值为负数时，start,stop默认交换位置。采用此法，可可得逆序数组，如下：

In [234]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [236]:
x[5::-2]

array([5, 3, 1])

多维数组

In [239]:
x2

array([[4, 9, 2, 0],
       [8, 2, 7, 8],
       [4, 4, 1, 9]])

In [242]:
x2[:2,:3]#两行三列

array([[4, 9, 2],
       [8, 2, 7]])

In [250]:
x2[:,::2] #所有行和1,3列

array([[4, 2],
       [8, 7],
       [4, 1]])

In [256]:
x2[::-1,::-1] #二维数组也可以进行逆序，每个维度都逆序

array([[9, 1, 4, 4],
       [8, 7, 2, 8],
       [0, 2, 9, 4]])

获取数组的行和列，可以将索引与切片组合起来实现此功能，“，”前面的代表行，后面代表列。

In [258]:
print(x2[:,0])

[4 8 4]


In [259]:
print(x2[0,:])

[4 9 2 0]


In [286]:
print(x2)

[[99  9  2  0]
 [ 8  2  7  8]
 [ 4  4  1  9]]


##### numpy切片，返回的是数组的视图。而python切片返回的值是副本。

In [263]:
x2_sub=x2[:2,:2]

In [264]:
x2_sub

array([[4, 9],
       [8, 2]])

In [265]:
x2_sub[0,0]=99

In [266]:
x2_sub

array([[99,  9],
       [ 8,  2]])

In [271]:
print(x2)  

[[99  9  2  0]
 [ 8  2  7  8]
 [ 4  4  1  9]]


##### 由此表明，修改数组的子数组原始数组也会被修改。
这意味着，当处理大型数据时，可以通过获取处理这些数据级的片段，而不用复制底层数据的缓存。







如何使用Numpy得到数组的副本？.copy

In [278]:
x2_sub_copy=x2[:2,:2].copy()

In [280]:
print(x2_sub_copy)

[[99  9]
 [ 8  2]]


In [282]:
x2_sub_copy[0,0]=88

In [283]:
x2_sub_copy

array([[88,  9],
       [ 8,  2]])

In [287]:
x2

array([[99,  9,  2,  0],
       [ 8,  2,  7,  8],
       [ 4,  4,  1,  9]])

所以，修改x2的副本x2_sub_copy，并没有修改x2

## 数组的变形

In [292]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [294]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [296]:
x=np.array([1,2,3])

In [297]:
x

array([1, 2, 3])

In [299]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [303]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

## 数组的拼接和分裂

In [315]:
x=np.array([1,2,3])

In [318]:
y=np.array([6,7,8])

In [319]:
z=np.array([10,20,30])

In [321]:
np.concatenate([x,y,z])

array([ 1,  2,  3,  6,  7,  8, 10, 20, 30])

In [323]:
grid=np.array([[1,2,3],
               [4,5,6]]
             )

In [327]:
np.concatenate([grid,grid],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [329]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [358]:
x=np.array([1,2])
x1=np.array([[1,2]])
y=np.array([[3,4],
            [99,100]])
grid=np.array([[1,6],
               [2,9]])

In [359]:
np.vstack([grid,x])

array([[1, 6],
       [2, 9],
       [1, 2]])

In [360]:
np.vstack([grid,x1])

array([[1, 6],
       [2, 9],
       [1, 2]])

In [363]:
np.hstack([y,grid])

array([[  3,   4,   1,   6],
       [ 99, 100,   2,   9]])

In [357]:
np.dstack

<function numpy.lib.shape_base.dstack>

In [348]:
z=np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]],
            [[11,12,13],
             [14,15,16],
             [17,18,19]]])

In [367]:
np.vstack([z,z])

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [369]:
np.hstack([z,z])

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19],
        [11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

## 数组的分裂

In [375]:
x=np.array([0,1,2,3,4,5,6,7,8])
x1,x2,x3=np.split(x,[3,5])

In [376]:
x1,x2,x3

(array([0, 1, 2]), array([3, 4]), array([5, 6, 7, 8]))

In [380]:
grid=np.arange(16).reshape((4,4))

In [382]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [384]:
np.vsplit(grid,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [386]:
np.hsplit(grid,[3])

[array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14]]), array([[ 3],
        [ 7],
        [11],
        [15]])]