In [5]:
import numpy as np

In [6]:
x=np.array([1,2,3,4,5])
np.random.shuffle(x)
x

array([5, 4, 3, 2, 1])

In [7]:
np.any(x[:-1]<x[1:])

False

In [8]:
import numpy as np

In [9]:
def selection_sort(x):
    for i in range(len(x)):
        swap=i+np.argmin(x[i:])
        (x[i],x[swap])=(x[swap],x[i])
    return x

In [10]:
selection_sort(np.array([2,1,4,3,5]))


array([1, 2, 3, 4, 5])

In [11]:
x=np.array([2,1,4,3,5])

In [12]:
np.sort(x)#原始数组不改变，仅返回排好序的数组
x

array([2, 1, 4, 3, 5])

In [13]:
x.sort()#注意这二者的区别，此处返回的是改变了的原始数组。
x

array([1, 2, 3, 4, 5])

In [14]:
x=np.array([2,1,4,3,5])

In [15]:
i=np.argsort(x)
i,x[i]

(array([1, 0, 3, 2, 4], dtype=int64), array([1, 2, 3, 4, 5]))

In [16]:
rand=np.random.RandomState(42)

In [17]:
x=rand.randint(0,10,(4,6))
print(x)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [18]:
x.sort(axis=1)
x

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [19]:
x.sort(axis=0)
x

array([[0, 1, 4, 5, 5, 7],
       [1, 2, 4, 5, 7, 7],
       [2, 3, 4, 6, 7, 9],
       [3, 4, 6, 6, 7, 9]])

In [29]:
y=rand.randint(0,10,(4,6))

In [30]:
y

array([[6, 7, 2, 0, 3, 1],
       [7, 3, 1, 5, 5, 9],
       [3, 5, 1, 9, 1, 9],
       [3, 7, 6, 8, 7, 4]])

In [31]:
np.sort(y,axis=0)

array([[3, 3, 1, 0, 1, 1],
       [3, 5, 1, 5, 3, 4],
       [6, 7, 2, 8, 5, 9],
       [7, 7, 6, 9, 7, 9]])

x与y的区别在于，x使用x.sort将自己修改了。而y使用了np.sort(x)仅返回排好序的数组

In [22]:
np.partition(x,2,axis=0)

array([[0, 1, 4, 5, 5, 7],
       [1, 2, 4, 5, 7, 7],
       [2, 3, 4, 6, 7, 9],
       [3, 4, 6, 6, 7, 9]])

In [36]:
x=np.array([7,2,3,1,6,5,4])
np.partition(x,2,axis=0)#为何上一个axis=0是按照列来排序，而此处是按照行来排序

array([1, 2, 3, 7, 6, 5, 4])

In [55]:
y=np.random.randint(0,10,(12,10))

In [56]:
y

array([[9, 1, 4, 0, 1, 9, 7, 6, 9, 8],
       [1, 7, 0, 5, 0, 1, 6, 2, 5, 6],
       [6, 8, 5, 6, 0, 6, 7, 1, 8, 6],
       [2, 4, 4, 0, 8, 6, 0, 2, 1, 8],
       [4, 7, 1, 4, 1, 3, 9, 2, 8, 6],
       [6, 5, 6, 3, 1, 4, 8, 3, 5, 7],
       [3, 2, 1, 9, 3, 3, 7, 6, 8, 9],
       [2, 4, 4, 2, 7, 7, 2, 9, 5, 4],
       [9, 0, 7, 4, 7, 8, 6, 0, 6, 7],
       [0, 6, 0, 9, 2, 3, 8, 6, 2, 7],
       [8, 9, 1, 7, 7, 6, 1, 3, 4, 1],
       [0, 1, 4, 1, 8, 9, 2, 4, 3, 4]])

In [58]:
np.partition(y,2,axis=0)

array([[0, 0, 0, 0, 0, 1, 0, 0, 1, 1],
       [0, 1, 0, 0, 0, 3, 1, 1, 2, 4],
       [1, 1, 1, 1, 1, 3, 2, 2, 3, 4],
       [2, 4, 4, 5, 8, 6, 7, 2, 9, 8],
       [4, 7, 5, 4, 1, 9, 9, 2, 8, 6],
       [6, 5, 6, 3, 1, 4, 8, 3, 5, 7],
       [3, 2, 1, 9, 3, 6, 7, 6, 8, 9],
       [2, 4, 4, 2, 7, 7, 7, 9, 5, 6],
       [9, 7, 7, 4, 7, 8, 6, 6, 6, 7],
       [9, 6, 4, 9, 2, 3, 8, 6, 5, 7],
       [8, 9, 1, 7, 7, 6, 6, 3, 4, 8],
       [6, 8, 4, 6, 8, 9, 2, 4, 8, 6]])

In [61]:
np.partition(y,5,axis=1)

array([[1, 4, 1, 0, 6, 7, 8, 9, 9, 9],
       [1, 0, 0, 1, 2, 5, 5, 6, 6, 7],
       [6, 0, 5, 1, 6, 6, 6, 7, 8, 8],
       [0, 0, 1, 2, 2, 4, 4, 6, 8, 8],
       [3, 1, 1, 2, 4, 4, 6, 9, 8, 7],
       [3, 3, 1, 4, 5, 5, 6, 8, 6, 7],
       [2, 3, 1, 3, 3, 6, 7, 8, 9, 9],
       [2, 2, 2, 4, 4, 4, 5, 7, 7, 9],
       [4, 0, 0, 6, 6, 7, 7, 8, 7, 9],
       [2, 0, 0, 2, 3, 6, 6, 7, 9, 8],
       [1, 1, 1, 3, 4, 6, 7, 9, 7, 8],
       [1, 2, 0, 1, 3, 4, 4, 9, 4, 8]])