In [3]:
import pandas as pd
import numpy as np

In [19]:
vals1=np.array([1,None,3,4])

In [20]:
vals1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [12]:
vals1,vals1.dtype

(array([1, None, 3, 4], dtype=object), dtype('O'))

In [21]:
for dtype in ['object','int']:
    print('dtype=',dtype)
    %timeit np.arange(1e6,dtype=dtype).sum()
    print()

dtype= object
62.9 ms ± 244 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype= int
2.35 ms ± 39.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)



In [27]:
vals2=np.array([1,np.nan,3,4])
vals2

array([ 1., nan,  3.,  4.])

In [29]:
vals2.dtype

dtype('float64')

In [31]:
vals2+2

array([ 3., nan,  5.,  6.])

In [36]:
vals2.sum(),vals2.min(),vals2.max()

C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_methods.py:29: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims)
C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_methods.py:26: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims)


(nan, nan, nan)

In [42]:
np.nansum(vals2),np.nanmin(vals2),np.nanmax(vals2)

(8.0, 1.0, 4.0)

pamdas中nan与None是可以等价交换的

In [47]:
x=pd.Series(range(2),dtype=int)
x

0    0
1    1
dtype: int32

In [46]:
pd.Series([1,np.nan,2,None])#将整数数组的缺失值强制转换为浮点数。

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [51]:
x[0]=None

In [55]:
x#pandas自动将None转换为nan

0    NaN
1    1.0
dtype: float64

处理缺失值

In [56]:
#发现缺失值

In [58]:
data=pd.Series([1,np.nan,'hello',None])

In [59]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [61]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [63]:
data[data.isnull()]

1     NaN
3    None
dtype: object

In [65]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [66]:
#剔除缺失值

In [68]:
data.dropna()

0        1
2    hello
dtype: object

In [69]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [97]:
df=pd.DataFrame([[1,np.nan,2],
                [2,3,2],
                [np.nan,4,6]])

In [99]:
df[3]=np.nan

In [102]:
df.dropna(axis='columns',how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  2
2  NaN  4.0  6

In [103]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  2 NaN
2  NaN  4.0  6 NaN

In [107]:
df.dropna(axis='rows',thresh=2)

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  2 NaN
2  NaN  4.0  6 NaN

In [108]:
#填充缺失值

In [110]:
a=np.array([1,np.nan,2,None,3])

In [114]:
data1=pd.DataFrame(a,index=list('abcde'))
data1

0
a     1
b   NaN
c     2
d  None
e     3

In [126]:
data1.fillna(method='ffill')

0
a  1
b  1
c  2
d  2
e  3

In [123]:
data1.fillna(method='bfill')

0
a  1
b  2
c  2
d  3
e  3

In [127]:
data1.fillna(0)

0
a  1
b  0
c  2
d  0
e  3

In [134]:
b=[{'a':i,'b':2*i,'c':3} for i in range(4)]

In [139]:
data2=pd.DataFrame(b)
data2

a  b  c
0  0  0  3
1  1  2  3
2  2  4  3
3  3  6  3