# 比较、掩码和布尔逻辑

In [17]:
import numpy as np

操作布尔数组

In [3]:
x=np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [4]:
x<3,x>3,x>=3,x<=3,x==3,x!=3,x**2==2**x

(array([ True,  True, False, False, False]),
 array([False, False, False,  True,  True]),
 array([False, False,  True,  True,  True]),
 array([ True,  True,  True, False, False]),
 array([False, False,  True, False, False]),
 array([ True,  True, False,  True,  True]),
 array([False,  True, False,  True, False]))

In [5]:
rng=np.random.RandomState(0)
rng

In [6]:
x=rng.randint(10,size=(3,4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [7]:
x<6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [8]:
print(x)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [9]:
np.count_nonzero(x<6)

8

In [10]:
np.sum(x<6)

8

In [18]:
np.sum(x<6,axis=0)

array([2, 2, 2, 2])

In [22]:
np.sum((x<6)&(x>2))

6

In [12]:
np.any(x>8)

True

In [13]:
np.any(x<0)

False

In [14]:
np.all(x>8)

False

In [15]:
np.all(x<10)

True

In [16]:
np.all(x==6)

False

将布尔数组作为掩码

In [25]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [27]:
x<5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [40]:
x[x<5]   
#即将一个数组与维度相同的布尔数组叠加，将True对应的值挑出来。
#布尔数组即掩码，False值将会掩盖与之对应的元素。

array([0, 3, 3, 3, 2, 4])

关键字and和or是对整个对象执行单个布尔运算。&和|是对对象的内容执行多个布尔运算。如下：

In [42]:
bool(42),bool(0)

(True, False)

In [54]:
bool(42 and 0),bool(42 or 0)#将42和0都看作整体进行比较

(False, True)

In [55]:
bin(42),bin(59)

('0b101010', '0b111011')

In [60]:
bin(42&59),bin(42|59) #对比特位(0,b,1)进行比较得到最终的结果。

('0b101010', '0b111011')

所以在进行numpy数组运算时，一般使用&和|.使用and和or会报错，如下：

In [74]:
a=np.array([1,1,1,0,0,0],dtype=bool)
b=np.array([0,1,0,1,0,1],dtype=bool)

In [76]:
a|b,a&b

(array([ True,  True,  True,  True, False,  True]),
 array([False,  True, False, False, False, False]))

In [78]:
a and b

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [80]:
a or b

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()