# Numpy 数组的计算---- 通用函数

In [71]:
import numpy as np

In [72]:
import time

In [73]:
time.clock()

1839.6646583138217

In [74]:
def test_time(function,values):
    start=time.clock()
    a=function(values)
    end=time.clock()
    return end-start,a
#定义函数计算函数执行时间，并返回相应函数值

In [75]:
def compute_reciprocals(values):
    output=np.empty(len(values))
    for i in range(len(values)):
        output[i]=1./values[i]
    return output
#定义一个函数，遍历数组中每个元素，求其倒数，然后返回所有元素倒数组成的数组

In [76]:
values=np.random.randint(1,10,size=20000)

In [77]:
test_time(compute_reciprocals,values)

(0.057861630945581055,
 array([0.25      , 0.33333333, 0.125     , ..., 0.5       , 0.11111111,
        0.16666667]))

In [67]:
%timeit compute_reciprocals(values) #%timeit用于返回函数执行的时间，所以无须自定义。

38.4 ms ± 718 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [80]:
%timeit  1./values #由此可见，直接对数组进行操作，更快。

30.3 µs ± 644 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### 简单的对数组执行某一操作，该操作将会被用于数组的每一个元素

In [99]:
x=np.array([1,2,3,4,5,6])

In [102]:
y=np.arange(10,70,10)

In [103]:
y

array([10, 20, 30, 40, 50, 60])

In [107]:
x/y #注意维度相同的数组才能够进行相除

array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

In [112]:
z=np.arange(9).reshape((3,3))
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [116]:
z**2#数组中每个元素的平方

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]], dtype=int32)

In [124]:
2**z#将数组作为2的指数，进行计算，将每个元素做指数运算，仍得到3*3维的数组

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

### 通过通用函数对向量进行计算总比使用python循环来得快。所以，实践中碰到循环，考虑是否能够使用向量计算代替。

Numpy的通用函数包括：算数运算符，绝对值，三角函数，反三角函数，指数对数，专用的通用函数

In [127]:
x=np.array([1,2,3,4,5,])

In [129]:
x+2

array([3, 4, 5, 6, 7])

In [131]:
x-2

array([-1,  0,  1,  2,  3])

In [133]:
x*2

array([ 2,  4,  6,  8, 10])

In [135]:
-x

array([-1, -2, -3, -4, -5])

In [137]:
x/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [139]:
x//2

array([0, 1, 1, 2, 2], dtype=int32)

In [141]:
x**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [143]:
x%2

array([1, 0, 1, 0, 1], dtype=int32)

In [145]:
y=np.array([-1,-2,-3,-4,-5])

In [147]:
np.abs(y)

array([1, 2, 3, 4, 5])

In [149]:
np.absolute(x)

array([1, 2, 3, 4, 5])

In [151]:
theta=np.linspace(0,np.pi,3)
theta

array([0.        , 1.57079633, 3.14159265])

In [153]:
np.sin(theta)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [155]:
np.cos(theta)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [156]:
np.tan(theta)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

In [165]:
z=np.array([-1,0,1])
z

array([-1,  0,  1])

In [167]:
np.arccos(z),np.arcsin(z),np.arctan(z)

(array([3.14159265, 1.57079633, 0.        ]),
 array([-1.57079633,  0.        ,  1.57079633]),
 array([-0.78539816,  0.        ,  0.78539816]))

In [172]:
x=np.array([1,2,3])
print(1**x,2**x,3**x,np.e**x)

[1 1 1] [2 4 8] [ 3  9 27] [ 2.71828183  7.3890561  20.08553692]


In [174]:
y=np.array([1,2,4,8])

In [176]:
np.log(y),np.log2(y),np.log10(y)

(array([0.        , 0.69314718, 1.38629436, 2.07944154]),
 array([0., 1., 2., 3.]),
 array([0.        , 0.30103   , 0.60205999, 0.90308999]))

In [179]:
z=np.array([0,0.001,0.01,0.1])

In [190]:
np.expm1(x)

array([ 1.71828183,  6.3890561 , 19.08553692])

In [192]:
np.log1p(x)

array([0.69314718, 1.09861229, 1.38629436])

### 专用的通用函数

In [202]:
from scipy import special

In [194]:
x=np.array([1,5,10])

In [195]:
special.gamma(x)

array([1.0000e+00, 2.4000e+01, 3.6288e+05])

In [198]:
special.gammaln(x)

array([ 0.        ,  3.17805383, 12.80182748])

In [201]:
special.beta(x,2)

array([0.5       , 0.03333333, 0.00909091])

## 高级的通用函数特性

通过out参数制定输出结果的存放位置

In [223]:
x=np.arange(5)
x

array([0, 1, 2, 3, 4])

In [224]:
y=np.empty(5)
y

array([50., 50., 50., 50., 50.])

In [225]:
np.multiply(x,10,out=y)

array([ 0., 10., 20., 30., 40.])

In [227]:
y

array([ 0., 10., 20., 30., 40.])

In [233]:
z=np.zeros(10)
z[::2]

array([0., 0., 0., 0., 0.])

In [239]:
np.power(2,x)

array([ 1,  2,  4,  8, 16], dtype=int32)

In [238]:
np.power(2,x,out=z[::2])

array([ 1.,  2.,  4.,  8., 16.])

In [241]:
z

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

#聚合,reduce方法，会将给定的操作重复的运用到每个元素上

In [243]:
x=np.arange(1,6)
x

array([1, 2, 3, 4, 5])

In [246]:
np.add.reduce(x)

15

In [249]:
np.multiply.reduce(x)    

120

外积，示例：使用一行代码实现一个乘法表

In [253]:
x=np.arange(1,6)
y=np.arange(1,2)

In [257]:
np.multiply.outer(x,y) #任何通用函数，都可以使用outer方法获得两个不同的数组元素对的运算结果,二维数组（len(x),len(y）)

array([[1],
       [2],
       [3],
       [4],
       [5]])