In [1]:
import numpy as np

In [3]:
import pandas as pd

In [5]:
def make_df(col,ind):
    data={c:[str(c)+str(i) for i in ind] for c in col}
    return pd.DataFrame(data,ind)

In [21]:
make_df('ABCD',range(3))

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2

numpy数组合并回顾

In [8]:
x=[1,2,3]

In [9]:
y=[4,5,6]

In [10]:
z=[7,8,9]

In [12]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
h=[[1,2],[3,4]]
h

[[1, 2], [3, 4]]

In [16]:
l=[[5,6],[7,8]]

In [18]:
np.concatenate([h,l],axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [22]:
np.concatenate([h,l],axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

通过pd.concat实现简易合并 

In [23]:
ser1=pd.Series(['a','b','c'],index=[1,2,3])

In [25]:
ser2=pd.Series(['d','e','f'],index=[4,5,6])

In [27]:
pd.concat([ser1,ser2])

1    a
2    b
3    c
4    d
5    e
6    f
dtype: object

In [33]:
df1=make_df('AB',[1,2])
df2=make_df('CD',[3,4])

In [39]:
df1

A   B
1  A1  B1
2  A2  B2

In [40]:
df2

C   D
3  C3  D3
4  C4  D4

In [44]:
pd.concat([df1,df2],axis=1)#行索引和列索引都进行了合并。

A    B    C    D
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3  NaN  NaN   C3   D3
4  NaN  NaN   C4   D4