# 层级索引

In [100]:
import numpy as np

In [10]:
import pandas as pd

In [46]:
index0=[('california',2000),('california',2010),('new york',2000),('new york',2010),('texas',2000),('texas',2010)]

In [47]:
populations=[3000000,30000012,50000000,50000034,10000023,10000033]

In [49]:
pop=pd.Series(populations,index=index0)

In [50]:
pop

(california, 2000)     3000000
(california, 2010)    30000012
(new york, 2000)      50000000
(new york, 2010)      50000034
(texas, 2000)         10000023
(texas, 2010)         10000033
dtype: int64

In [19]:
pop[('california',2000):('texas',2000)]

(california, 2000)     3000000
(california, 2010)    30000012
(new york, 2000)      50000000
(new york, 2010)      50000034
(texas, 2000)         10000023
dtype: int64

In [51]:
pop[[i for i in pop.index if i[1]==2010]]


(california, 2010)    30000012
(new york, 2010)      50000034
(texas, 2010)         10000033
dtype: int64

pandas多级索引

In [64]:
index2=pd.MultiIndex.from_tuples(index1)
index2

MultiIndex(levels=[['california', 'new york', 'texas'], [2000, 2010]],
           labels=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

In [67]:
pop=pop.reindex(index2)
pop

california  2000     3000000
            2010    30000012
new york    2000    50000000
            2010    50000034
texas       2000    10000023
            2010    10000033
dtype: int64

In [78]:
pop['california']

2000     3000000
2010    30000012
dtype: int64

高维数据多级索引

In [80]:
 pop_df=pop.unstack()

In [83]:
pop_df

2000      2010
california   3000000  30000012
new york    50000000  50000034
texas       10000023  10000033

In [86]:
pop_df.stack()

california  2000     3000000
            2010    30000012
new york    2000    50000000
            2010    50000034
texas       2000    10000023
            2010    10000033
dtype: int64

In [90]:
pop_df1=pd.DataFrame({'total':pop,'under18':[9087899,234567,433666,788888,999999,888888]})
pop_df1

total  under18
california 2000   3000000  9087899
           2010  30000012   234567
new york   2000  50000000   433666
           2010  50000034   788888
texas      2000  10000023   999999
           2010  10000033   888888

In [93]:
fu_18=pop_df1['total']/pop_df1['under18']
fu_18

california  2000      0.330109
            2010    127.895279
new york    2000    115.296103
            2010     63.380396
texas       2000     10.000033
            2010     11.250048
dtype: float64

In [96]:
fu_18.unstack()

2000        2010
california    0.330109  127.895279
new york    115.296103   63.380396
texas        10.000033   11.250048

多级索引的创建方法

In [103]:
df=pd.DataFrame(np.random.rand(4,2),index=[['a','a','b','b'],[1,2,1,2]],columns=['data1','data2'])
df

data1     data2
a 1  0.499471  0.885459
  2  0.142877  0.266823
b 1  0.480141  0.625076
  2  0.168404  0.430700

In [105]:
df.unstack()

data1               data2          
          1         2         1         2
a  0.499471  0.142877  0.885459  0.266823
b  0.480141  0.168404  0.625076  0.430700

In [107]:
data={('a',1):2000,('a',2):2002,('b',1):3000,('d',1):4000}
data

{('a', 1): 2000, ('a', 2): 2002, ('b', 1): 3000, ('d', 1): 4000}

In [109]:
pd.Series(data)

a  1    2000
   2    2002
b  1    3000
d  1    4000
dtype: int64

显式创建多级索引

In [114]:
pd.MultiIndex.from_arrays([['a','a','b','b'],[1,2,1,2]])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [116]:
pd.MultiIndex.from_tuples([('a',1),('a',2),('b',1),('b',2)])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [118]:
pd.MultiIndex.from_product([['a','b'],[1,2]])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [121]:
pd.MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [124]:
pop.index.names=['state','year']
pop

state       year
california  2000     3000000
            2010    30000012
new york    2000    50000000
            2010    50000034
texas       2000    10000023
            2010    10000033
dtype: int64

多级列索引

In [127]:
index=pd.MultiIndex.from_product([[2013,2014],[1,2]],names=['year','visit'])
index

MultiIndex(levels=[[2013, 2014], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]],
           names=['year', 'visit'])

In [130]:
columns=pd.MultiIndex.from_product([['bob','guido','sue'],['hr','temp']],names=['subject','type'])
columns

MultiIndex(levels=[['bob', 'guido', 'sue'], ['hr', 'temp']],
           labels=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]],
           names=['subject', 'type'])

In [156]:
data=np.round(np.random.randn(4,6),1)
data

array([[-1.2, -0.2, -0.7,  0.4,  0.4,  1.1],
       [ 0.7, -0.6, -1.2, -0. ,  0.7,  0. ],
       [ 1.7,  0.5,  0.5,  0.3,  1.1,  0.4],
       [-1.7,  2.1,  1.2, -2.4, -1.3,  1. ]])

In [157]:
data[:,::2]*=10

In [158]:
data+=37

In [160]:
data

array([[25. , 36.8, 30. , 37.4, 41. , 38.1],
       [44. , 36.4, 25. , 37. , 44. , 37. ],
       [54. , 37.5, 42. , 37.3, 48. , 37.4],
       [20. , 39.1, 49. , 34.6, 24. , 38. ]])

In [162]:
health_data=pd.DataFrame(data,index=index,columns=columns)
health_data

subject      bob       guido         sue      
type          hr  temp    hr  temp    hr  temp
year visit                                    
2013 1      25.0  36.8  30.0  37.4  41.0  38.1
     2      44.0  36.4  25.0  37.0  44.0  37.0
2014 1      54.0  37.5  42.0  37.3  48.0  37.4
     2      20.0  39.1  49.0  34.6  24.0  38.0

In [174]:
health_data['bob']['temp']

year  visit
2013  1        36.8
      2        36.4
2014  1        37.5
      2        39.1
Name: temp, dtype: float64

In [193]:
health_data[health_data.bob>30]

subject      bob       guido         sue      
type          hr  temp    hr  temp    hr  temp
year visit                                    
2013 1       NaN  36.8   NaN  37.4   NaN  38.1
     2      44.0  36.4  25.0  37.0  44.0  37.0
2014 1      54.0  37.5  42.0  37.3  48.0  37.4
     2       NaN  39.1   NaN  34.6   NaN  38.0

series多级索引取值和切片

In [195]:
pop

state       year
california  2000     3000000
            2010    30000012
new york    2000    50000000
            2010    50000034
texas       2000    10000023
            2010    10000033
dtype: int64

In [197]:
pop['california',2000]

3000000

In [199]:
pop['california']

year
2000     3000000
2010    30000012
dtype: int64

In [205]:
pop.loc['california':'new york']

state       year
california  2000     3000000
            2010    30000012
new york    2000    50000000
            2010    50000034
dtype: int64

In [207]:
pop[:,2010]

state
california    30000012
new york      50000034
texas         10000033
dtype: int64

In [213]:
pop[pop>2000000]

state       year
california  2000     3000000
            2010    30000012
new york    2000    50000000
            2010    50000034
texas       2000    10000023
            2010    10000033
dtype: int64

In [215]:
pop[['california','texis']]

state       year
california  2000     3000000
            2010    30000012
dtype: int64

dataframe多级索引

In [217]:
health_data

subject      bob       guido         sue      
type          hr  temp    hr  temp    hr  temp
year visit                                    
2013 1      25.0  36.8  30.0  37.4  41.0  38.1
     2      44.0  36.4  25.0  37.0  44.0  37.0
2014 1      54.0  37.5  42.0  37.3  48.0  37.4
     2      20.0  39.1  49.0  34.6  24.0  38.0

In [219]:
health_data['bob','hr']

year  visit
2013  1        25.0
      2        44.0
2014  1        54.0
      2        20.0
Name: (bob, hr), dtype: float64

In [221]:
health_data.iloc[:3,:2]

subject      bob      
type          hr  temp
year visit            
2013 1      25.0  36.8
     2      44.0  36.4
2014 1      54.0  37.5

In [223]:
health_data.loc[:,('bob','hr')]

year  visit
2013  1        25.0
      2        44.0
2014  1        54.0
      2        20.0
Name: (bob, hr), dtype: float64

In [224]:
idx=pd.IndexSlice

In [226]:
health_data.loc[idx[:,1],idx[:,'hr']]

subject      bob guido   sue
type          hr    hr    hr
year visit                  
2013 1      25.0  30.0  41.0
2014 1      54.0  42.0  48.0

多级索引行列转换

In [244]:
index1=pd.MultiIndex.from_product([['a','c','b'],[2,1]])

In [246]:
index1

MultiIndex(levels=[['a', 'b', 'c'], [1, 2]],
           labels=[[0, 0, 2, 2, 1, 1], [1, 0, 1, 0, 1, 0]])

In [247]:
data=np.random.rand(6)
data

array([0.4874558 , 0.45362875, 0.34330559, 0.35666155, 0.41641163,
       0.87059681])

In [251]:
data=pd.Series(data,index=index1)
data

a  2    0.487456
   1    0.453629
c  2    0.343306
   1    0.356662
b  2    0.416412
   1    0.870597
dtype: float64

In [254]:
data.index.names=['char','int']

In [256]:
data

char  int
a     2      0.487456
      1      0.453629
c     2      0.343306
      1      0.356662
b     2      0.416412
      1      0.870597
dtype: float64

In [261]:
data['a':'b']#报错原因是多层索引排列时，没有进行按顺序排序。每层都需要按序排序

UnsortedIndexError: 'Key length (1) was greater than MultiIndex lexsort depth (0)'

In [277]:
data1=data.sort_index()


In [278]:
data1

char  int
a     1      0.453629
      2      0.487456
b     1      0.870597
      2      0.416412
c     1      0.356662
      2      0.343306
dtype: float64

In [288]:
data1['a':'b']

char  int
a     1      0.453629
      2      0.487456
b     1      0.870597
      2      0.416412
dtype: float64

In [289]:
pop

state       year
california  2000     3000000
            2010    30000012
new york    2000    50000000
            2010    50000034
texas       2000    10000023
            2010    10000033
dtype: int64

In [285]:
pop.unstack(level=1)

year            2000      2010
state                         
california   3000000  30000012
new york    50000000  50000034
texas       10000023  10000033

In [290]:
pop.unstack(level=0)

state  california  new york     texas
year                                 
2000      3000000  50000000  10000023
2010     30000012  50000034  10000033

In [297]:
pop.unstack().stack()

state       year
california  2000     3000000
            2010    30000012
new york    2000    50000000
            2010    50000034
texas       2000    10000023
            2010    10000033
dtype: int64

In [301]:
pop_flat=pop.reset_index(name='population')
pop_flat

state  year  population
0  california  2000     3000000
1  california  2010    30000012
2    new york  2000    50000000
3    new york  2010    50000034
4       texas  2000    10000023
5       texas  2010    10000033

In [307]:
pop_flat.set_index(['state','year'])
#在实际情况中，常常需要将表格中的某些列转换成多级索引。与reset_inex正好相反。

population
state      year            
california 2000     3000000
           2010    30000012
new york   2000    50000000
           2010    50000034
texas      2000    10000023
           2010    10000033

In [318]:
pop.loc[:,2000].min()

3000000

In [323]:
health_data.mean(level='year')

subject   bob       guido          sue       
type       hr  temp    hr   temp    hr   temp
year                                         
2013     34.5  36.6  27.5  37.20  42.5  37.55
2014     37.0  38.3  45.5  35.95  36.0  37.70

In [324]:
health_data.mean(level='year').mean(axis=1,level='type')

type         hr       temp
year                      
2013  34.833333  37.116667
2014  39.500000  37.316667